# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/dotnet:2.0-sdk

pipelines:
  default:
    - step:
        name: Build MQTTserver
        caches:
          - dotnetcore
        script: # Modify the commands below to build your repository.
          - dotnet restore
          - dotnet publish MQTTserver -c release -o build
        artifacts: 
          - MQTTserver/build/**
    - step:
        name: Run Tests
        caches:
          - dotnetcore
        script: # Modify the commands below to build your repository.
          - dotnet restore
          - dotnet test Tests 
    - step:
        name: Publish the container
        caches:
          - dotnetcore
        script: # Modify the commands below to build your repository.
          - cd MQTTserver
          - docker login hub.docker.com -u $dockerHubUsername -p $dockerHubPWD
        services: 
          - docker